### ISSUE TITLE
Replacing Global:[Environment] module with a custom [Environment] class is ill-advised

### ISSUE THREAD

**Issue by glachancecmaisonneuve** [rbuckton/posh-vsdev#1]
In one switft move, you disable a whole lot of useful functions like:
- [Environment]::ExpandEnvironmentVariables
- [Environment]::GetCommandLineArgs
- [Environment]::GetEnvironmentVariable
- [Environment]::GetEnvironmentVariables
- [Environment]::GetFolderPath
- [Environment]::GetLogicalDrives
- [Environment]::SetEnvironmentVariable
- [Environment]::CommandLine
- [Environment]::CurrentDirectory
- [Environment]::MachineName
- [Environment]::NewLine
- [Environment]::OSVersion
- [Environment]::ProcessorCount
- [Environment]::StackTrace
- [Environment]::SystemDirectory
- [Environment]::SystemPageSize
- [Environment]::TickCount
- [Environment]::UserDomainName
- [Environment]::UserInteractive
- [Environment]::UserName
- [Environment]::Version
- [Environment]::WorkingSet

If you need all the environment varialbles, clone the [Environment]::GetEnvironmentVariables() dictionnary and avoid well-known module names.

**Comment by glachancecmaisonneuve** [comment]
Formatting failed on me.  List of useful methods/attrbutes gone after importing your module:

```powershell
[Environment]::ExpandEnvironmentVariables
[Environment]::GetCommandLineArgs
[Environment]::GetEnvironmentVariable
[Environment]::GetEnvironmentVariables
[Environment]::GetFolderPath
[Environment]::GetLogicalDrives
[Environment]::ReferenceEquals
[Environment]::SetEnvironmentVariable
[Environment]::CommandLine
[Environment]::CurrentDirectory
[Environment]::CurrentManagedThreadId
[Environment]::ExitCode
[Environment]::HasShutdownStarted
[Environment]::Is64BitOperatingSystem
[Environment]::Is64BitProcess
[Environment]::MachineName
[Environment]::NewLine
[Environment]::OSVersion
[Environment]::ProcessorCount
[Environment]::StackTrace
[Environment]::SystemDirectory
[Environment]::SystemPageSize
[Environment]::TickCount
[Environment]::UserDomainName
[Environment]::UserInteractive
[Environment]::UserName
[Environment]::Version
[Environment]::WorkingSet

```

**Comment by rbuckton** [comment]
Does this actually replace the global Environment? The Environment class in `posh-vsdev.psm1` is not exported, so it shouldn't affect the global.

**Comment by glachancecmaisonneuve** [comment]
I may have made a mistake, I was actually adding group policy cachepath support to your extension and when I realized that I could not access [environment]::ExpandEnvironmentVariables and why, I assumed that would be true everywhere, 

It's probably only true in the module file (that's where I was working), as you have pointed out.

Besides that, someone would have said something by now.

Now I'm looking pretty dumb, something I try to avoid, especially If i'm about to make a pr.

**Comment by rbuckton** [comment]
No worries. You should be able to rename the `Environment` class in the module to work around this.
